name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./bUwUild.sh

  keyword:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./bUwUild.sh
    - name: keywords
      run: cd tests/ && g++ test_crit.cpp -l criterion && mv a.out .. && cd .. && ./a.out