name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./bUwUild.sh

  keyword:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./bUwUild.sh
    - name: criterion
      run: sudo add-apt-repository ppa:snaipewastaken/ppa && sudo apt-get install criterion-dev
    - name: keywords
      run: cd tests/ && g++ test_crit.cpp -l criterion && mv a.out .. && cd .. && ./a.out
    - name: test
      run: ./UWU